@ShopApi_HostAddress = http://localhost:5120

GET {{ShopApi_HostAddress}}/api/products
Accept: application/json
###

GET {{ShopApi_HostAddress}}/api/products/1
Accept: application/json
###

Get {{ShopApi_HostAddress}}/images/catalog1.jpg
###